name: choosifoodi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+2

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_sliders:
  flutter_switch:
  pinput:
  http:
  flutter_rating_stars:
  flutter_swiper_view:
  fluttertoast:
  get:
  url_launcher:
  cupertino_stepper:
  percent_indicator:
  shared_preferences:
  cupertino_icons:
  dots_indicator:
  dotted_border:
  syncfusion_flutter_datepicker: ^23.1.36
  geolocator:
  geocoding:
  uuid:
  webview_flutter:
  firebase_crashlytics:
  keyboard_hider:
  file_picker:
#  connectivity:
  connectivity_plus:
  flutter_contacts:
#  flutter_stripe:
  flutter_stripe: ^5.1.0
  syncfusion_flutter_xlsio:
  path_provider:
#  open_file:
  open_filex:
  firebase_core:
  firebase_messaging:
  flutter_local_notifications: ^13.0.0
  intl:
  google_sign_in:
  firebase_auth: ^4.9.0
  flutter_svg:
  image_picker:
  permission_handler:
  image_cropper:
  device_info_plus:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or setting resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins_regular.otf
          weight: 400
        - asset: assets/fonts/poppins_medium.otf
          weight: 500
        - asset: assets/fonts/poppins_bold.otf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
